repo_missing: fix packages appearing twice
Fix a regression from 11b2c4f4 ("pmb.core.config: Make "aports" variable
a Path rather than a list[Path]") that resulted in repo_missing
returning packages from the systemd repository twice, once as part of
the systemd repository (as it is supposed to be) and once as part of the
regular repository (wrong!).

I have noticed this because bpo refused the generated package lists
with:
  RuntimeError: pkgname found twice in payload with repo=None: gnome-settings-daemon-mobile

The gnome-settings-daemon-mobile package is really in both repositories:

  ./temp/gnome-settings-daemon-mobile
  ./extra-repos/systemd/gnome-settings-daemon-mobile

But due to the bug it appeared to be twice in the regular repository.
Adjust the code to fix this.

Signed-off-by: Oliver Smith <ollieparanoid@postmarketos.org>
Part-of: <https://gitlab.postmarketos.org/postmarketOS/pmbootstrap/-/merge_requests/3041>