pmb.install._install.get_recommends: respect !deps
While iterating through the pmb_recommends, make a list of packages that
are listed as not-to-be-installed in depends (e.g. !gnome-shell-mobile
in postmarketos-ui-gnome).

Use this list later when attempting to resolve the list of packages from
pmb_recommends with packages in pmaports. If a package is listed in
not_depends but provides a package we are looking for then do not use it
instead of the package listed in pmb_recommends.

This fixes that GNOME can currently not be installed in Nura edge:

ERROR: unable to select packages:
  gnome-shell-mobile-schemas-999948.0-r5:
    breaks: postmarketos-ui-gnome-5-r0[!gnome-shell-mobile-schemas]
    satisfies: gnome-shell-mobile-999948.0-r5[gnome-shell-mobile-schemas]
  gnome-settings-daemon-mobile-999948.0-r3:
    breaks: postmarketos-ui-gnome-5-r0[!gnome-settings-daemon-mobile]
    satisfies: gdm-999951.0-r0[gnome-settings-daemon]
               mutter-mobile-999948.0-r3[gnome-settings-daemon-mobile]
  mutter-mobile-schemas-999948.0-r3:
    breaks: postmarketos-ui-gnome-5-r0[!mutter-mobile-schemas]
    satisfies: mutter-mobile-999948.0-r3[mutter-mobile-schemas]
  mutter-mobile-999948.0-r3:
    breaks: postmarketos-ui-gnome-5-r0[!mutter-mobile]
    satisfies: gnome-shell-mobile-999948.0-r5[mutter-mobile]
               gnome-shell-mobile-999948.0-r5[so:libmutter-16.so.0]
               gnome-shell-mobile-999948.0-r5[so:libmutter-clutter-16.so.0]
               gnome-shell-mobile-999948.0-r5[so:libmutter-cogl-16.so.0]
               gnome-shell-mobile-999948.0-r5[so:libmutter-mtk-16.so.0]
  gnome-shell-mobile-999948.0-r5:
    breaks: postmarketos-ui-gnome-5-r0[!gnome-shell-mobile]
    satisfies: gdm-999951.0-r0[gnome-shell]
               gnome-51.0-r0[gnome-shell]
               gnome-mobile-extensions-app-999948.0-r5[gnome-shell-mobile]

Regarding the datatype, use "set" instead of "list" so we have each
package only in there once and .remove() may not leave another one in
there. Ideally we would use set everywhere instead of lists for the
packages to be installed, as it does not make sense to ask apk to
install the same package twice. However doing this is some more effort
and I mainly want to fix a bug so let's do this another time.

Signed-off-by: Oliver Smith <ollieparanoid@postmarketos.org>
Part-of: <https://gitlab.postmarketos.org/postmarketOS/pmbootstrap/-/merge_requests/3053>