pmb.flasher.variables: fix typo
_partition_vendor_boot -> partition_vendor_boot, otherwise some of the
flash methods fail with:

ERROR: cannot access local variable 'partition_vendor_boot' where it
is not associated with a value

Fixes: 8e3229c9a8d4 ("pmb: support bootimg v3/v4 and `vendor_boot`")

Part-of: https://gitlab.postmarketos.org/postmarketOS/pmbootstrap/-/merge_requests/2667