aportgen/gcc: don't use tracedeps
After recent refactoring of the upstream gcc package, running tracedeps
on our generated gcc cross packages did not work anymore:

  >>> ERROR: gcc-aarch64*: libc.musl-aarch64.so.1: path not found

The gcc packages were manually adjusted (thanks Luca and Clayton!) to
not use tracedeps, and the dependencies were added manually as
workaround. Do the same programmatically in pmbootstrap aportgen code
for now, so generating new cross aports works again.

This is actually better than using tracedeps, because with the new
method the gcc cross packages don't immediately break anymore when gcc
gets changed in Alpine.

Related: issue 2517
Related: pmaports MR 5722
Related: https://gitlab.alpinelinux.org/alpine/aports/-/commit/77d4639539972ee1821327114af63d3dbce0a1ec#f094e438feb3f38f32fdb25d55a0a9d7cfaabca7

Part-of: https://gitlab.postmarketos.org/postmarketOS/pmbootstrap/-/merge_requests/2521