pmb.parse.kconfig.check: fix crash when trying to flash Alpine kernels
This fixes a bug when trying to flash an Alpine kernel. The
aport doesn't exist in pmaports when `flasher/frontend.py` calls
`pmb.parse.kconfig.check`:

  File "/home/a/pmbootstrap/pmb/commands/flasher.py", line 43, in run
    kernel(
  File "/home/a/pmbootstrap/pmb/flasher/frontend.py", line 38, in kernel
    pmb.parse.kconfig.check(flavor, must_exist=False)
  File "/home/a/pmbootstrap/pmb/parse/kconfig.py", line 262, in check
    apkbuild = pmb.parse.apkbuild(aport / "APKBUILD")
                                  ~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'